fix(just): fix syntax error
introduced in 083532b8ff

error: Recipe line has inconsistent leading whitespace. Recipe started with `␠␠␠␠␠` but found line with `␠␠␠␠`
——▶ Justfile:341:1
│
341 │     set -eoux pipefail
│ ^^^^